spring:
  application:
    name: car-rental-service

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/car_rental?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root

  sql:
    init:
      mode: always
      data-locations: classpath:db/data.sql

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

    defer-datasource-initialization: true
    generate-ddl: true

logging:
  config: classpath:logback-local.xml

server:
  port: 8090

springdoc:
  swagger-ui:
    path: /swagger-ui.html

  api-docs:
    path: /api-docs

carrental:
  openapi:
    url: http://localhost:8090
