### 자동차 생성 API 호출
POST {{base}}/cars
Content-Type: application/json
Accept: application/json

{
  "car": {
    "manufacturer": "Hyundai",
    "model": "Tucson",
    "productionYear": 2023,
    "categories": [
      1,
      2
    ]
  }
}

### 자동차 렌탈 가능여부 API 호출
GET {{base}}/cars/1