### 자동차 등록
POST {{base}}/cars
Content-Type: application/json
Accept: application/json

{
  "car": {
    "manufacturer": "Hyundai",
    "model": "Tucson",
    "productionYear": 2023,
    "categories": [
      1,
      2
    ]
  }
}

### 자동차 대여 가능 여부 조회
GET {{base}}/cars/1